name: Linux build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Prerequisites
      run: |
        sudo apt install -y libgmp-dev
        ln -sf /usr/lib/x86_64-linux-gnu/libgmp* ${{github.workspace}}/3rdParty/lib/
        ln -sf /usr/include/gmpxx.h ${{github.workspace}}/3rdParty/include/
        ln -sf /usr/include/x86_64-linux-gnu/gmp.h ${{github.workspace}}/3rdParty/include/

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
   
    - name: upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: nash-release
        path: ${{ github.workspace }}/build/nash
        if-no-files-found: error
    - name: upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: mnash-release
        path: ${{ github.workspace }}/build/mnash
        if-no-files-found: error
