name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download and Install libGMP
        run: |
          (New-Object Net.WebClient).DownloadFile('https://github.com/ShiftMediaProject/gmp/releases/download/6.1.2-6/libgmp_6.1.2-6_msvc15.zip', "${env:GITHUB_WORKSPACE}\3rdParty\libgmp.zip")
          Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory("${env:GITHUB_WORKSPACE}\3rdParty\libgmp.zip", "${env:GITHUB_WORKSPACE}\3rdParty")

      - name: create solution file
        run: |
          cd build
          cmake .. -G "Visual Studio 16 2019"
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: run msbuild release
        run: msbuild "${env:GITHUB_WORKSPACE}\build\nash.sln" /p:Configuration=Release
      - name: run msbuild debug
        run: msbuild "${env:GITHUB_WORKSPACE}\build\nash.sln" /p:Configuration=Debug
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: nash-release
          path: ${{ github.workspace }}/build/Release/nash.exe
          if-no-files-found: error
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: nash-debug
          path: ${{ github.workspace }}/build/Debug/nash.exe
          if-no-files-found: error
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: mnash-release
          path: ${{ github.workspace }}/build/Release/mnash.exe
          if-no-files-found: error
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: mnash-debug
          path: ${{ github.workspace }}/build/Debug/mnash.exe
          if-no-files-found: error
